language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer update

script:
  - vendor/bin/phpunit --coverage-text
  - cd examples && ../vendor/bin/behat
